name: Croppers
main: me.lasillje.croppers.Croppers
version: 1.0.1
api-version: 1.13
author: alphalawz
commands:
   cropper:
      description: Main cropper command
      usage: /<command> <type> [player]
